// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: cache.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CacheType int32

const (
	CacheType_string CacheType = 0
	CacheType_int    CacheType = 1
)

// Enum value maps for CacheType.
var (
	CacheType_name = map[int32]string{
		0: "string",
		1: "int",
	}
	CacheType_value = map[string]int32{
		"string": 0,
		"int":    1,
	}
)

func (x CacheType) Enum() *CacheType {
	p := new(CacheType)
	*p = x
	return p
}

func (x CacheType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CacheType) Descriptor() protoreflect.EnumDescriptor {
	return file_cache_proto_enumTypes[0].Descriptor()
}

func (CacheType) Type() protoreflect.EnumType {
	return &file_cache_proto_enumTypes[0]
}

func (x CacheType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CacheType.Descriptor instead.
func (CacheType) EnumDescriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{0}
}

type Cache struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Type          CacheType              `protobuf:"varint,2,opt,name=type,proto3,enum=network.v1.CacheType" json:"type,omitempty"`
	Ttl           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Value         *anypb.Any             `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cache) Reset() {
	*x = Cache{}
	mi := &file_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cache) ProtoMessage() {}

func (x *Cache) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cache.ProtoReflect.Descriptor instead.
func (*Cache) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{0}
}

func (x *Cache) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Cache) GetType() CacheType {
	if x != nil {
		return x.Type
	}
	return CacheType_string
}

func (x *Cache) GetTtl() *timestamppb.Timestamp {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *Cache) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type ReadCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	MaxAge        *Duration              `protobuf:"bytes,2,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCacheRequest) Reset() {
	*x = ReadCacheRequest{}
	mi := &file_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCacheRequest) ProtoMessage() {}

func (x *ReadCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCacheRequest.ProtoReflect.Descriptor instead.
func (*ReadCacheRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{1}
}

func (x *ReadCacheRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReadCacheRequest) GetMaxAge() *Duration {
	if x != nil {
		return x.MaxAge
	}
	return nil
}

type ReadCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cache         *Cache                 `protobuf:"bytes,1,opt,name=cache,proto3" json:"cache,omitempty"`
	Hit           bool                   `protobuf:"varint,2,opt,name=hit,proto3" json:"hit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCacheResponse) Reset() {
	*x = ReadCacheResponse{}
	mi := &file_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCacheResponse) ProtoMessage() {}

func (x *ReadCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCacheResponse.ProtoReflect.Descriptor instead.
func (*ReadCacheResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{2}
}

func (x *ReadCacheResponse) GetCache() *Cache {
	if x != nil {
		return x.Cache
	}
	return nil
}

func (x *ReadCacheResponse) GetHit() bool {
	if x != nil {
		return x.Hit
	}
	return false
}

type StoreCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Ttl           *Duration              `protobuf:"bytes,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Type          CacheType              `protobuf:"varint,3,opt,name=type,proto3,enum=network.v1.CacheType" json:"type,omitempty"`
	Value         *anypb.Any             `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreCacheRequest) Reset() {
	*x = StoreCacheRequest{}
	mi := &file_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreCacheRequest) ProtoMessage() {}

func (x *StoreCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreCacheRequest.ProtoReflect.Descriptor instead.
func (*StoreCacheRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{3}
}

func (x *StoreCacheRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreCacheRequest) GetTtl() *Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *StoreCacheRequest) GetType() CacheType {
	if x != nil {
		return x.Type
	}
	return CacheType_string
}

func (x *StoreCacheRequest) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type StoreCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	HasOverriden  bool                   `protobuf:"varint,2,opt,name=has_overriden,json=hasOverriden,proto3" json:"has_overriden,omitempty"`
	Ttl           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreCacheResponse) Reset() {
	*x = StoreCacheResponse{}
	mi := &file_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreCacheResponse) ProtoMessage() {}

func (x *StoreCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreCacheResponse.ProtoReflect.Descriptor instead.
func (*StoreCacheResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{4}
}

func (x *StoreCacheResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreCacheResponse) GetHasOverriden() bool {
	if x != nil {
		return x.HasOverriden
	}
	return false
}

func (x *StoreCacheResponse) GetTtl() *timestamppb.Timestamp {
	if x != nil {
		return x.Ttl
	}
	return nil
}

var File_cache_proto protoreflect.FileDescriptor

const file_cache_proto_rawDesc = "" +
	"\n" +
	"\vcache.proto\x12\n" +
	"network.v1\x1a\x0eduration.proto\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x01\n" +
	"\x05Cache\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.network.v1.CacheTypeR\x04type\x12,\n" +
	"\x03ttl\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03ttl\x12*\n" +
	"\x05value\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\x05value\"S\n" +
	"\x10ReadCacheRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\amax_age\x18\x02 \x01(\v2\x14.network.v1.DurationR\x06maxAge\"N\n" +
	"\x11ReadCacheResponse\x12'\n" +
	"\x05cache\x18\x01 \x01(\v2\x11.network.v1.CacheR\x05cache\x12\x10\n" +
	"\x03hit\x18\x02 \x01(\bR\x03hit\"\xa4\x01\n" +
	"\x11StoreCacheRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x03ttl\x18\x02 \x01(\v2\x14.network.v1.DurationR\x03ttl\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.network.v1.CacheTypeR\x04type\x12*\n" +
	"\x05value\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\x05value\"y\n" +
	"\x12StoreCacheResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\rhas_overriden\x18\x02 \x01(\bR\fhasOverriden\x12,\n" +
	"\x03ttl\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03ttl* \n" +
	"\tCacheType\x12\n" +
	"\n" +
	"\x06string\x10\x00\x12\a\n" +
	"\x03int\x10\x012\xa5\x01\n" +
	"\fCacheService\x12H\n" +
	"\tReadCache\x12\x1c.network.v1.ReadCacheRequest\x1a\x1d.network.v1.ReadCacheResponse\x12K\n" +
	"\n" +
	"StoreCache\x12\x1d.network.v1.StoreCacheRequest\x1a\x1e.network.v1.StoreCacheResponseB5Z3beloin.com/distributed-cache/internal/network/protob\x06proto3"

var (
	file_cache_proto_rawDescOnce sync.Once
	file_cache_proto_rawDescData []byte
)

func file_cache_proto_rawDescGZIP() []byte {
	file_cache_proto_rawDescOnce.Do(func() {
		file_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_proto_rawDesc), len(file_cache_proto_rawDesc)))
	})
	return file_cache_proto_rawDescData
}

var file_cache_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cache_proto_goTypes = []any{
	(CacheType)(0),                // 0: network.v1.CacheType
	(*Cache)(nil),                 // 1: network.v1.Cache
	(*ReadCacheRequest)(nil),      // 2: network.v1.ReadCacheRequest
	(*ReadCacheResponse)(nil),     // 3: network.v1.ReadCacheResponse
	(*StoreCacheRequest)(nil),     // 4: network.v1.StoreCacheRequest
	(*StoreCacheResponse)(nil),    // 5: network.v1.StoreCacheResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 7: google.protobuf.Any
	(*Duration)(nil),              // 8: network.v1.Duration
}
var file_cache_proto_depIdxs = []int32{
	0,  // 0: network.v1.Cache.type:type_name -> network.v1.CacheType
	6,  // 1: network.v1.Cache.ttl:type_name -> google.protobuf.Timestamp
	7,  // 2: network.v1.Cache.value:type_name -> google.protobuf.Any
	8,  // 3: network.v1.ReadCacheRequest.max_age:type_name -> network.v1.Duration
	1,  // 4: network.v1.ReadCacheResponse.cache:type_name -> network.v1.Cache
	8,  // 5: network.v1.StoreCacheRequest.ttl:type_name -> network.v1.Duration
	0,  // 6: network.v1.StoreCacheRequest.type:type_name -> network.v1.CacheType
	7,  // 7: network.v1.StoreCacheRequest.value:type_name -> google.protobuf.Any
	6,  // 8: network.v1.StoreCacheResponse.ttl:type_name -> google.protobuf.Timestamp
	2,  // 9: network.v1.CacheService.ReadCache:input_type -> network.v1.ReadCacheRequest
	4,  // 10: network.v1.CacheService.StoreCache:input_type -> network.v1.StoreCacheRequest
	3,  // 11: network.v1.CacheService.ReadCache:output_type -> network.v1.ReadCacheResponse
	5,  // 12: network.v1.CacheService.StoreCache:output_type -> network.v1.StoreCacheResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_cache_proto_init() }
func file_cache_proto_init() {
	if File_cache_proto != nil {
		return
	}
	file_duration_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_proto_rawDesc), len(file_cache_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cache_proto_goTypes,
		DependencyIndexes: file_cache_proto_depIdxs,
		EnumInfos:         file_cache_proto_enumTypes,
		MessageInfos:      file_cache_proto_msgTypes,
	}.Build()
	File_cache_proto = out.File
	file_cache_proto_goTypes = nil
	file_cache_proto_depIdxs = nil
}
