// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: distributed.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_distributed_proto protoreflect.FileDescriptor

const file_distributed_proto_rawDesc = "" +
	"\n" +
	"\x11distributed.proto\x12\n" +
	"network.v1B5Z3beloin.com/distributed-cache/internal/network/protob\x06proto3"

var file_distributed_proto_goTypes = []any{}
var file_distributed_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_distributed_proto_init() }
func file_distributed_proto_init() {
	if File_distributed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_distributed_proto_rawDesc), len(file_distributed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_distributed_proto_goTypes,
		DependencyIndexes: file_distributed_proto_depIdxs,
	}.Build()
	File_distributed_proto = out.File
	file_distributed_proto_goTypes = nil
	file_distributed_proto_depIdxs = nil
}
