// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: duration.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Unit int32

const (
	Unit_Second Unit = 0
	Unit_Minute Unit = 1
	Unit_Hour   Unit = 2
	Unit_Day    Unit = 3
)

// Enum value maps for Unit.
var (
	Unit_name = map[int32]string{
		0: "Second",
		1: "Minute",
		2: "Hour",
		3: "Day",
	}
	Unit_value = map[string]int32{
		"Second": 0,
		"Minute": 1,
		"Hour":   2,
		"Day":    3,
	}
)

func (x Unit) Enum() *Unit {
	p := new(Unit)
	*p = x
	return p
}

func (x Unit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Unit) Descriptor() protoreflect.EnumDescriptor {
	return file_duration_proto_enumTypes[0].Descriptor()
}

func (Unit) Type() protoreflect.EnumType {
	return &file_duration_proto_enumTypes[0]
}

func (x Unit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Unit.Descriptor instead.
func (Unit) EnumDescriptor() ([]byte, []int) {
	return file_duration_proto_rawDescGZIP(), []int{0}
}

type Duration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          Unit                   `protobuf:"varint,1,opt,name=unit,proto3,enum=network.v1.Unit" json:"unit,omitempty"`
	Value         uint64                 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Duration) Reset() {
	*x = Duration{}
	mi := &file_duration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Duration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duration) ProtoMessage() {}

func (x *Duration) ProtoReflect() protoreflect.Message {
	mi := &file_duration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duration.ProtoReflect.Descriptor instead.
func (*Duration) Descriptor() ([]byte, []int) {
	return file_duration_proto_rawDescGZIP(), []int{0}
}

func (x *Duration) GetUnit() Unit {
	if x != nil {
		return x.Unit
	}
	return Unit_Second
}

func (x *Duration) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_duration_proto protoreflect.FileDescriptor

const file_duration_proto_rawDesc = "" +
	"\n" +
	"\x0eduration.proto\x12\n" +
	"network.v1\"F\n" +
	"\bDuration\x12$\n" +
	"\x04unit\x18\x01 \x01(\x0e2\x10.network.v1.UnitR\x04unit\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value*1\n" +
	"\x04Unit\x12\n" +
	"\n" +
	"\x06Second\x10\x00\x12\n" +
	"\n" +
	"\x06Minute\x10\x01\x12\b\n" +
	"\x04Hour\x10\x02\x12\a\n" +
	"\x03Day\x10\x03B5Z3beloin.com/distributed-cache/internal/network/protob\x06proto3"

var (
	file_duration_proto_rawDescOnce sync.Once
	file_duration_proto_rawDescData []byte
)

func file_duration_proto_rawDescGZIP() []byte {
	file_duration_proto_rawDescOnce.Do(func() {
		file_duration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_duration_proto_rawDesc), len(file_duration_proto_rawDesc)))
	})
	return file_duration_proto_rawDescData
}

var file_duration_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_duration_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_duration_proto_goTypes = []any{
	(Unit)(0),        // 0: network.v1.Unit
	(*Duration)(nil), // 1: network.v1.Duration
}
var file_duration_proto_depIdxs = []int32{
	0, // 0: network.v1.Duration.unit:type_name -> network.v1.Unit
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_duration_proto_init() }
func file_duration_proto_init() {
	if File_duration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_duration_proto_rawDesc), len(file_duration_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_duration_proto_goTypes,
		DependencyIndexes: file_duration_proto_depIdxs,
		EnumInfos:         file_duration_proto_enumTypes,
		MessageInfos:      file_duration_proto_msgTypes,
	}.Build()
	File_duration_proto = out.File
	file_duration_proto_goTypes = nil
	file_duration_proto_depIdxs = nil
}
