// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: restore.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RestoreService_Restore_FullMethodName = "/network.v1.RestoreService/Restore"
)

// RestoreServiceClient is the client API for RestoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestoreServiceClient interface {
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RestoreResponse], error)
}

type restoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRestoreServiceClient(cc grpc.ClientConnInterface) RestoreServiceClient {
	return &restoreServiceClient{cc}
}

func (c *restoreServiceClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RestoreResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RestoreService_ServiceDesc.Streams[0], RestoreService_Restore_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RestoreRequest, RestoreResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RestoreService_RestoreClient = grpc.ServerStreamingClient[RestoreResponse]

// RestoreServiceServer is the server API for RestoreService service.
// All implementations must embed UnimplementedRestoreServiceServer
// for forward compatibility.
type RestoreServiceServer interface {
	Restore(*RestoreRequest, grpc.ServerStreamingServer[RestoreResponse]) error
	mustEmbedUnimplementedRestoreServiceServer()
}

// UnimplementedRestoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRestoreServiceServer struct{}

func (UnimplementedRestoreServiceServer) Restore(*RestoreRequest, grpc.ServerStreamingServer[RestoreResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedRestoreServiceServer) mustEmbedUnimplementedRestoreServiceServer() {}
func (UnimplementedRestoreServiceServer) testEmbeddedByValue()                        {}

// UnsafeRestoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestoreServiceServer will
// result in compilation errors.
type UnsafeRestoreServiceServer interface {
	mustEmbedUnimplementedRestoreServiceServer()
}

func RegisterRestoreServiceServer(s grpc.ServiceRegistrar, srv RestoreServiceServer) {
	// If the following call pancis, it indicates UnimplementedRestoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RestoreService_ServiceDesc, srv)
}

func _RestoreService_Restore_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RestoreRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RestoreServiceServer).Restore(m, &grpc.GenericServerStream[RestoreRequest, RestoreResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RestoreService_RestoreServer = grpc.ServerStreamingServer[RestoreResponse]

// RestoreService_ServiceDesc is the grpc.ServiceDesc for RestoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RestoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "network.v1.RestoreService",
	HandlerType: (*RestoreServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Restore",
			Handler:       _RestoreService_Restore_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "restore.proto",
}
