// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: restore.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batch         uint32                 `protobuf:"varint,1,opt,name=batch,proto3" json:"batch,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_restore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_restore_proto_rawDescGZIP(), []int{0}
}

func (x *RestoreRequest) GetBatch() uint32 {
	if x != nil {
		return x.Batch
	}
	return 0
}

func (x *RestoreRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caches        []*Cache               `protobuf:"bytes,1,rep,name=caches,proto3" json:"caches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_restore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_restore_proto_rawDescGZIP(), []int{1}
}

func (x *RestoreResponse) GetCaches() []*Cache {
	if x != nil {
		return x.Caches
	}
	return nil
}

var File_restore_proto protoreflect.FileDescriptor

const file_restore_proto_rawDesc = "" +
	"\n" +
	"\rrestore.proto\x12\n" +
	"network.v1\x1a\vcache.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"V\n" +
	"\x0eRestoreRequest\x12\x14\n" +
	"\x05batch\x18\x01 \x01(\rR\x05batch\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\"<\n" +
	"\x0fRestoreResponse\x12)\n" +
	"\x06caches\x18\x01 \x03(\v2\x11.network.v1.CacheR\x06caches2V\n" +
	"\x0eRestoreService\x12D\n" +
	"\aRestore\x12\x1a.network.v1.RestoreRequest\x1a\x1b.network.v1.RestoreResponse0\x01B5Z3beloin.com/distributed-cache/internal/network/protob\x06proto3"

var (
	file_restore_proto_rawDescOnce sync.Once
	file_restore_proto_rawDescData []byte
)

func file_restore_proto_rawDescGZIP() []byte {
	file_restore_proto_rawDescOnce.Do(func() {
		file_restore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_restore_proto_rawDesc), len(file_restore_proto_rawDesc)))
	})
	return file_restore_proto_rawDescData
}

var file_restore_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_restore_proto_goTypes = []any{
	(*RestoreRequest)(nil),        // 0: network.v1.RestoreRequest
	(*RestoreResponse)(nil),       // 1: network.v1.RestoreResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*Cache)(nil),                 // 3: network.v1.Cache
}
var file_restore_proto_depIdxs = []int32{
	2, // 0: network.v1.RestoreRequest.from:type_name -> google.protobuf.Timestamp
	3, // 1: network.v1.RestoreResponse.caches:type_name -> network.v1.Cache
	0, // 2: network.v1.RestoreService.Restore:input_type -> network.v1.RestoreRequest
	1, // 3: network.v1.RestoreService.Restore:output_type -> network.v1.RestoreResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_restore_proto_init() }
func file_restore_proto_init() {
	if File_restore_proto != nil {
		return
	}
	file_cache_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_restore_proto_rawDesc), len(file_restore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_restore_proto_goTypes,
		DependencyIndexes: file_restore_proto_depIdxs,
		MessageInfos:      file_restore_proto_msgTypes,
	}.Build()
	File_restore_proto = out.File
	file_restore_proto_goTypes = nil
	file_restore_proto_depIdxs = nil
}
